name: pospell
on:
  issue_comment:
    types:
      - edited
      - created

jobs:
  fix-spell:
    name: Fix spelling
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'pospell-fix' }}
    steps:
      - name: Confirmar ejecucion
        continue-on-error: true
        run: |
          curl ${{github.event.comment.url}}/reactions \
            -X POST \
            -d '{"content":"+1"}' \
            -H "Accept: application/vnd.github.squirrel-girl-preview+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/checkout@v3
      - name: Preparar Python v3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Instalar dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y hunspell hunspell-es gettext
          python -m pip install -r requirements.txt
      - name: Ejecutar Powrap
        run: powrap --quiet **/*.po
      - name: Revisar con Pospell
        run: python scripts/check_spell.py
        continue-on-error: true
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          message: "auto: spell check"
          github_token: ${{ secrets.GITHUB_TOKEN }}
